catalogMode: prefer
ignoreWorkspaceRootCheck: true
shamefullyHoist: true
shellEmulator: true
strictPeerDependencies: false
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
  - chokidar@4.0.3

packages: []

catalogs:
  dev:
    '@types/eslint-plugin-jsx-a11y': ^6.10.1
    '@types/node': ^25.0.3
    '@typescript/native-preview': 7.0.0-dev.20251213.1
    bumpp: ^10.3.2
    eslint-typegen: ^2.3.0
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
    svelte: ^5.46.0
    tailwindcss: ^4.1.18
    tsdown: ^0.17.4
    tsx: ^4.21.0
    typescript: ~5.9.3
  internal:
    '@antfu/install-pkg': ^1.1.0
    '@clack/prompts': ^0.11.0
    eslint: ^9.39.2
    eslint-flat-config-utils: ^2.1.4
    eslint-merge-processors: ^2.0.0
    find-up-simple: 1.0.1
    globals: ^16.5.0
    local-pkg: 1.1.2
  parsers:
    '@typescript-eslint/parser': ^8.50.0
    jsonc-eslint-parser: ^2.4.2
    svelte-eslint-parser: ^1.4.1
    toml-eslint-parser: ^0.10.1
    yaml-eslint-parser: ^1.3.2
  plugins:
    '@eslint-community/eslint-plugin-eslint-comments': ^4.5.0
    '@eslint-react/eslint-plugin': ^2.3.13
    '@eslint/markdown': ^7.5.1
    '@next/eslint-plugin-next': ^16.1.0
    '@stylistic/eslint-plugin': ^5.6.1
    '@typescript-eslint/eslint-plugin': ^8.50.0
    '@vitest/eslint-plugin': ^1.5.4
    eslint-config-flat-gitignore: ^2.1.0
    eslint-plugin-ariel: ^0.0.3
    eslint-plugin-better-tailwindcss: ^3.8.0
    eslint-plugin-de-morgan: ^2.0.0
    eslint-plugin-import-lite: ^0.3.1
    eslint-plugin-jsdoc: ^61.5.0
    eslint-plugin-jsonc: ^2.21.0
    eslint-plugin-jsx-a11y: ^6.10.2
    eslint-plugin-n: ^17.23.1
    eslint-plugin-no-only-tests: ^3.3.0
    eslint-plugin-perfectionist: ^4.15.1
    eslint-plugin-pnpm: ^1.4.3
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.26
    eslint-plugin-regexp: ^2.10.0
    eslint-plugin-solid: ^0.14.5
    eslint-plugin-svelte: ^3.13.1
    eslint-plugin-toml: ^0.12.0
    eslint-plugin-unicorn: ^62.0.0
    eslint-plugin-unused-imports: ^4.3.0
    eslint-plugin-yml: ^1.19.1

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
