packages: []

catalog:
  '@antfu/install-pkg': ^1.1.0
  '@clack/prompts': ^0.11.0
  eslint: ^9.31.0
  eslint-flat-config-utils: ^2.1.0
  eslint-merge-processors: ^2.0.0
  globals: ^16.3.0
  local-pkg: 1.1.1

catalogs:
  dev:
    '@types/node': ^24.0.14
    '@typescript/native-preview': 7.0.0-dev.20250716.1
    bumpp: ^10.2.0
    eslint-typegen: ^2.2.1
    svelte: ^5.36.5
    tailwindcss: ^4.1.11
    tsdown: ^0.12.9
    tsx: ^4.20.3
    typescript: ^5.8.3
  parsers:
    jsonc-eslint-parser: ^2.4.0
    svelte-eslint-parser: ^1.3.0
    toml-eslint-parser: ^0.10.0
    yaml-eslint-parser: ^1.3.0
  plugins:
    '@eslint-community/eslint-plugin-eslint-comments': ^4.5.0
    '@eslint/markdown': ^7.0.0
    '@stylistic/eslint-plugin': ^5.2.0
    '@typescript-eslint/eslint-plugin': ^8.37.0
    '@typescript-eslint/parser': ^8.37.0
    '@vitest/eslint-plugin': ^1.3.4
    eslint-config-flat-gitignore: ^2.1.0
    eslint-plugin-ariel: ^0.0.2
    eslint-plugin-better-tailwindcss: ^3.6.2
    eslint-plugin-de-morgan: ^1.3.0
    eslint-plugin-import-lite: ^0.3.0
    eslint-plugin-jsdoc: ^51.4.1
    eslint-plugin-jsonc: ^2.20.1
    eslint-plugin-n: ^17.21.0
    eslint-plugin-no-only-tests: ^3.3.0
    eslint-plugin-perfectionist: ^4.15.0
    eslint-plugin-pnpm: ^1.0.0
    eslint-plugin-regexp: ^2.9.0
    eslint-plugin-svelte: ^3.11.0
    eslint-plugin-toml: ^0.12.0
    eslint-plugin-unicorn: ^59.0.1
    eslint-plugin-unused-imports: ^4.1.4
    eslint-plugin-yml: ^1.18.0

onlyBuiltDependencies:
  - esbuild
